MVC_CRUD/Controllers/CountryController.cs
using MVC_CRUD.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_CRUD.Controllers
{
    public class CountryController : Controller
    {
        TestDbEntities db;
        public CountryController()
        {
            db = new TestDbEntities();
        }
        // GET: Country
        public ActionResult Index()
        {
            var countries = (from row in db.tblCountries select row).ToList();

            return View(countries);
        }
        public ActionResult GetAllBanks(int? id)
        {
            if (User != null)
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault()
                + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var code = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault();
                var name = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt16(start) : 0;
                int recordsTotal = 0;
                int? c_id = clsGetSchoolId.GetSchoolId(User.UserId);
                List<clsBank> Banks = (from b in db.tblBanks
                                       orderby b.BankId descending
                                       where b.SchoolId == c_id
                                       select new clsBank
                                       {
                                           BankId = b.BankId,
                                           BankName = b.BankName,
                                           Code = b.Code,
                                           Status = b.Status
                                       }).ToList();
                decimal? Total = 0;
                foreach (clsBank b in Banks)
                {
                    b.StatementBalance = getBankAccountBalance(b.BankId);
                    b.StatementBalanceForShow = b.StatementBalance.ToString() + "_normal_" + b.BankId.ToString();
                    b.IdForShow = b.BankId + "-Transaction";
                    Total += b.StatementBalance;
                }
                clsBank bb = new clsBank();
                bb.BankId = 0;
                bb.BankName = "";
                bb.Code = "";
                bb.Status = "";
                bb.IdForShow = "0-Total";
                bb.StatementBalance = 0;
                bb.StatementBalanceForShow = Total.ToString() + "_bold_0";
                Banks.Add(bb);
                if (id > 0)
                {
                    Banks = Banks.Where(c => c.BankId.Equals(id)).ToList();
                }
                if (!string.IsNullOrEmpty(code))
                {
                    Banks = Banks.Where(c => c.Code.ToLower().Contains(code.ToLower())).ToList();
                }
                else if (!string.IsNullOrEmpty(name))
                {
                    Banks = Banks.Where(c => c.BankName.ToLower().Contains(name.ToLower())).ToList();
                }
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    Banks = Banks.OrderBy(sortColumn + " " + sortColumnDir).ToList();
                }
                ViewBag.Status = new SelectList(getStatus(), "Value", "Text", "Active");
                recordsTotal = Banks.Count();
                var data = Banks.Skip(skip).Take(pageSize).ToList();
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data },
                JsonRequestBehavior.AllowGet);

            }
            else
            {
                return RedirectToAction("login", "account");
            }
        }
        [HttpGet]
        public ActionResult AddUpdateCountry(int id = 0)
        {
            clsCountry country = new clsCountry();
            if (id > 0)
            {
                country = (from c in db.tblCountries
                        where c.CountryId == id
                        select new clsCountry
                        {
                            CountryId = c.CountryId,
                            CountryName = c.CountryName
                        }).FirstOrDefault();

            }
            else
            {
                country = new clsCountry
                {
                    CountryId = 0,
                    CountryName = ""
                };
            }      

            return PartialView(country);
        }
        [HttpPost]
        public ActionResult AddUpdateCountry(clsCountry country)
        {
            string message = "";
            bool status = false;
            try
            {
                string returnId = "0";
                string insertUpdateStatus = "";
                if (country.CountryId > 0)
                {
                    insertUpdateStatus = "Update";

                }
                else
                {
                    insertUpdateStatus = "Save";

                }
                returnId = InsertUpdateCountryDb(country, insertUpdateStatus);
                if (returnId == "Success")
                {
                    status = true;
                    message = "User Type Successfully Updated";
                }
                else
                {
                    status = false;
                    message = returnId;
                }
            }
            catch (Exception ex)
            {
                status = false;
                message = ex.Message.ToString();
            }

            return new JsonResult { Data = new { status = status, message = message } };
        }

        private string InsertUpdateCountryDb(clsCountry st, string insertUpdateStatus)
        {
            string returnId = "0";
            string connection = System.Configuration.ConfigurationManager.ConnectionStrings["ADO"].ConnectionString;
            using (SqlConnection con = new SqlConnection(connection))
            {
                try
                {
                    con.Open();
                    using (SqlCommand cmd = new SqlCommand("spInsertUpdateCountry", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.Clear();
                        cmd.Parameters.Add("@CountryId", SqlDbType.Int).Value = st.CountryId;
                        cmd.Parameters.Add("@CountryName", SqlDbType.NVarChar).Value = st.CountryName;
                        cmd.Parameters.Add("@InsertUpdateStatus", SqlDbType.NVarChar).Value = insertUpdateStatus;
                        cmd.Parameters.Add("@CheckReturn", SqlDbType.NVarChar, 300).Direction = ParameterDirection.Output;
                        cmd.ExecuteNonQuery();
                        returnId = cmd.Parameters["@CheckReturn"].Value.ToString();
                        cmd.Dispose();
                    }
                    con.Close();
                    con.Dispose();
                }
                catch (Exception ex)
                {
                    returnId = ex.Message.ToString();
                }
            }
            return returnId;
        }
        [HttpPost]
        public ActionResult DeleteCountry(int id)
        {
            string message = "";
            bool status = false;

            clsCountry st = new clsCountry();
            st.CountryId = id;
            string returnId = InsertUpdateCountryDb(st, "Delete");
            if (returnId == "Success")
            {
                ModelState.Clear();
                status = true;
                message = "User Type Successfully Deleted";
            }
            else
            {
                ModelState.Clear();
                status = false;
                message = returnId;
            }
            return new JsonResult { Data = new { status = status, message = message } };
        }
    }
}

MVC_CRUD/Views/Country/AddUpdateCountry.cshtml
@model MVC_CRUD.Models.clsCountry

@*@using (Html.BeginForm("AddUpdateCity", "Home", FormMethod.Post))*@
@* { *@
@*@Html.AntiForgeryToken()*@

<div class="form-horizontal">
    <h4>tblCountry</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CountryId, new { })

    <div class="form-group">
        @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default add" />
        </div>
    </div>
</div>
@* } *@


<script>
   
    $(document).on('click', '.add', function () {
        var Id = $('#CountryId').val();
        var CountryName = $('#CountryName').val();
        var country = {
            'CountryId': Id,
            'CountryName': CountryName
        }
        $.ajax({
            type: "POST",
            url: "/Country/AddUpdateCountry/",
            data: { 'country': country },
            dataType: 'json',
            success: function (response) {
                if (response.status) {
                    location.reload();
                }
                else {
                    alert(response.message);
                }
            }
        })
    })


   



</script>

MVC_CRUD/Views/Country/Index.cshtml
@model IEnumerable<MVC_CRUD.Models.tblCountry>

@{
    ViewBag.Title = "Home";
}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<h2>Countries</h2>

<div class="addEditDiv">
    @{Html.RenderAction("AddUpdateCountry", "Country", new { @id = 0 });}
</div>


<div class="abc">
    <div class="table-responsive">
        <table class="table table-bordered table-striped tblShadow" id="myTable" width="100%" cellspacing="0">
            <thead style="background-color: #007acc; color: white; ">
                <tr>
                
                    <th>Country Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>


</div>



<script>
    $(document).ready(function () {
        //$('#myTable').DataTable();
        var breakpointDefinition = {
            desktop: 1366,
            tablet: 1024,
            phone: 480
        };

        $('#myTable').dataTable({
            "sDom": '<"top">rt<"bottom"lp i><"clear">',
            "autoWidth": true,
            "bLengthChange": false,
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "/Country/GetAllCountries",
                "type": "POST",
                "datatype": "json",
                error: function (xhr, httpStatusMessage, customErrorMessage) {
                    if (xhr.status === 410) {
                        window.location.href = customErrorMessage;
                    }
                }
            },
            "columns": [
               
                { "data": "CountryName", "name": "CountryName", "autoWidth": true },
                {
                    "data": "CountryId", "width": "50px", "class": "Acenter", "orderable": false, "render": function (data) {
                        var edit = '<a title="Edit" class="edit" href="javascript:void(0)"  data-value="' + data + '"><i class="fa fa-fw fa-edit txt-color-blue"></i></a>&nbsp';
                        var del = '<a title="Delete" href="javascript:void(0)" class="deleteBtn" data-value="' + data + '" ><i class="fa fa-fw fa-times-circle txt-color-red"></i></a>';
                        var final = edit + del;
                        return final;
                    }
                }
            ]
        });
        oTable = $('#myTable').DataTable();

    });


    //Task2
    function getAllData() {
        var id = $(".id").text();
        return id;
    }
    $(document).on('click', '.edit', function () {
        var id = $(this).attr("data-value");
        LoadDiv(id);
    })
    function LoadDiv(id) {
        $.ajax({
            type: "GET",
            url: "/Country/AddUpdateCountry/" + id,
            success: function (response) {
                $('.addEditDiv').html(response);
            }
        })
    }
    //Delete
    $(document).on('click', '.deleteBtn', function () {
        var id = $(this).attr("data-value");
        Delete(id);
    })
    function Delete(id) {
        var checkstr = confirm('Are you sure you want to delete');
        if (checkstr == true) {
            $.ajax({
                url: "/Country/DeleteCountry/" + id,
                type: "POST",
                dataType: 'json',
                success: function (response) {
                    if (response.status) {
                        location.reload();
                    }
                    else {
                        alert(response.message);
                    }
                }
            })
        }
        else {
            return false;
        }
    }

</script>